server {
    listen 80;
    server_name _;
    root /var/www/payment-fe;
    index index.html;

    # Vite hashes asset filenames -> cache forever
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA: mọi route đều trả index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
}
