server {
    listen 80;
    server_name codetoolkit.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name codetoolkit.org;

    ssl_certificate     /etc/ssl/cloudflare/codetoolkit/codetoolkit/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/codetoolkit/codetoolkit/private.pem;

    root /var/www/payment-fe;
    index index.html;

    # Vite hashes asset filenames -> cache forever
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA: mọi route đều trả index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
}
